kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  namespace: train-prod
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8090
    nodePort: 30080




---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: train-prod
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: grocamador/cicd-demo:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
